import type {
  CaseRecord,
  FleetDrone,
  LiveSnapshot,
  MeshNode,
  Mission,
  Village,
} from '../types';

export const MOCK_VILLAGES: Village[] = [
  { village_name: 'Araku Valley', lat: 18.3273, lon: 82.8763 },
  { village_name: 'Paderu', lat: 18.0833, lon: 82.6667 },
  { village_name: 'Ananthagiri', lat: 18.2167, lon: 83.0167 },
  { village_name: 'Chintapalli', lat: 17.8833, lon: 82.5833 },
  { village_name: 'Munchingiputtu', lat: 18.35, lon: 82.55 },
];

export const MOCK_CASES: CaseRecord[] = [
  {
    case_id: 'mock-1',
    patient_name: 'Ramappa K.',
    age: 45,
    sex: 'M',
    asha_id: 'ASHA-001',
    asha_name: 'Lakshmi G.',
    village_name: 'Araku Valley',
    gps_lat: 18.3273,
    gps_lon: 82.8763,
    heart_rate: 112,
    spo2: 89,
    temperature_f: 101.4,
    systolic_bp: 95,
    diastolic_bp: 60,
    chief_complaint: 'snakebite',
    visual_severity_score: 18,
    visual_features: { puncture_depth: 'moderate', edema: 'high' },
    triage_score: 82,
    priority: 'P1',
    recommended_action: 'IMMEDIATE VTOL DISPATCH',
    suggested_payload: ['epipen_2pack', 'wound_dressing_kit'],
    vitals_flagged: [{ vital: 'SPO2', value: 89, severity: 'critical', points: 25, reason: 'Hypoxia detected' }],
    status: 'pending',
    doctor_reviewed: false,
    timestamp: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    case_id: 'mock-2',
    patient_name: 'Sita Devi',
    age: 28,
    sex: 'F',
    asha_id: 'ASHA-004',
    asha_name: 'Vanaja M.',
    village_name: 'Paderu',
    gps_lat: 18.0833,
    gps_lon: 82.6667,
    heart_rate: 88,
    spo2: 97,
    temperature_f: 98.6,
    systolic_bp: 110,
    diastolic_bp: 75,
    chief_complaint: 'pregnancy_complication',
    visual_severity_score: 5,
    visual_features: {},
    triage_score: 45,
    priority: 'P2',
    recommended_action: 'Monitor & Consult',
    suggested_payload: ['ors_sachets'],
    vitals_flagged: [],
    status: 'reviewed',
    doctor_reviewed: true,
    timestamp: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const MOCK_MESH_NODES: MeshNode[] = [
  {
    node_id: 'NODE-01',
    village_name: 'Araku Central',
    status: 'online',
    battery_pct: 85,
    last_seen: new Date().toISOString(),
    queue_depth: 0,
    lat: 18.3273,
    lng: 82.8763,
    link_quality: 0.92,
    hop_distance_to_hub: 0,
  },
  {
    node_id: 'NODE-02',
    village_name: 'Paderu North',
    status: 'online',
    battery_pct: 72,
    last_seen: new Date().toISOString(),
    queue_depth: 2,
    lat: 18.0833,
    lng: 82.6667,
    link_quality: 0.78,
    hop_distance_to_hub: 1,
  },
  {
    node_id: 'NODE-03',
    village_name: 'Chintapalli Relay',
    status: 'degraded',
    battery_pct: 12,
    last_seen: new Date().toISOString(),
    queue_depth: 5,
    lat: 17.8833,
    lng: 82.5833,
    link_quality: 0.45,
    hop_distance_to_hub: 2,
  }
];

export const MOCK_FLEET: FleetDrone[] = [
  {
    drone_id: 'VTOL-01',
    status: 'EN_ROUTE',
    battery_pct: 68,
    mission: null,
    current_lat: 18.2,
    current_lon: 82.7,
    eta_min: 12,
  },
  {
    drone_id: 'VTOL-02',
    status: 'STANDBY',
    battery_pct: 95,
    mission: null,
    current_lat: 18.3273,
    current_lon: 82.8763,
    eta_min: null,
  },
  {
    drone_id: 'VTOL-03',
    status: 'LANDING',
    battery_pct: 24,
    mission: null,
    current_lat: 18.0833,
    current_lon: 82.6667,
    eta_min: 2,
  }
];

export const MOCK_SNAPSHOT: LiveSnapshot = {
  active_missions: [],
  p1_alerts: MOCK_CASES.filter(c => c.priority === 'P1'),
  mesh_status_summary: { online: 8, degraded: 2, offline: 1 },
  drones_airborne: 3,
  cases_last_hour: 5,
  timestamp: new Date().toISOString(),
};
